name: "Terraform Smoketest"
description: "Assert that a module can be initialized and validated, and that the pre-commit hooks have been run."
inputs:
  aws_access_key_id:
    description: "AWS access key"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true
  aws_default_region:
    description: "Default AWS region"
    required: false
    default: "eu-west-1"
runs:
  using: docker
  image: docker://docker.pkg.github.com/skm-ice/terraform-smoketest-action/action:v3
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
    AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
